import { readFileSync, writeFileSync, mkdirSync, renameSync, existsSync } from 'node:fs';
import { join } from 'node:path';

export type Category = 'humor'|'gaming'|'animals'|'technology'|'music_art'|'other';
export interface YouTubeShortItem { id:string; videoId:string; category:Category; weight:number; enabled:boolean; addedAt:string }
export interface YouTubeShortsCatalog { schemaVersion:1; generatedAt:string; videos:YouTubeShortItem[] }
export interface LocalFeedback { videoId:string; category:Category; liked?:boolean; hidden?:boolean; impressions:number; completedViews:number; quickSkips:number; lastViewedAt?:string }
export function validateCatalog(value:unknown): YouTubeShortsCatalog | null { if(!value||typeof value!=='object')return null; const x=value as any;if(x.schemaVersion!==1||typeof x.generatedAt!=='string'||!Array.isArray(x.videos))return null;const seen=new Set<string>(),videos:YouTubeShortItem[]=[];for(const v of x.videos){if(!v||typeof v.id!=='string'||typeof v.videoId!=='string'||!/^[\w-]{6,}$/.test(v.videoId)||seen.has(v.videoId)||!['humor','gaming','animals','technology','music_art','other'].includes(v.category)||typeof v.weight!=='number'||!Number.isFinite(v.weight)||typeof v.enabled!=='boolean'||typeof v.addedAt!=='string')continue;if(v.enabled){seen.add(v.videoId);videos.push(v)}}return videos.length?{schemaVersion:1,generatedAt:x.generatedAt,videos}:null }
export function loadCatalog(opts:{fallback:YouTubeShortsCatalog;cacheFile:string;remoteUrl?:string;timeoutMs?:number}):YouTubeShortsCatalog { const read=(p:string)=>{try{return validateCatalog(JSON.parse(readFileSync(p,'utf8')))}catch{return null}}; if(opts.remoteUrl){ /* remote loading is intentionally opt-in at the caller; fallback is deterministic */ } return read(opts.cacheFile)??validateCatalog(opts.fallback)??opts.fallback }
export async function fetchRemoteCatalog(url:string, timeoutMs=4000, etag?:string):Promise<{catalog:YouTubeShortsCatalog|null;etag?:string;notModified?:boolean}>{
  try { const u=new URL(url); if(u.protocol!=='https:') return {catalog:null}; const c=new AbortController(); const t=setTimeout(()=>c.abort(),timeoutMs); const r=await fetch(u,{signal:c.signal,redirect:'error',headers:etag?{'If-None-Match':etag}:{}}); clearTimeout(t); if(r.status===304)return {catalog:null,notModified:true,etag}; if(!r.ok||Number(r.headers.get('content-length')??0)>2_000_000)return {catalog:null}; return {catalog:validateCatalog(await r.json()),etag:r.headers.get('etag')??undefined}; } catch { return {catalog:null} }
}
export function rankCatalog(items:readonly YouTubeShortItem[], feedback:readonly LocalFeedback[], seen:ReadonlySet<string>, rng= Math.random):YouTubeShortItem[]{const by=new Map(feedback.map(f=>[f.videoId,f]));return items.filter(v=>v.enabled&&!seen.has(v.videoId)&&!by.get(v.videoId)?.hidden).map(v=>{const f=by.get(v.videoId),bonus=Math.min(.25,(f?.liked? .15:0)+(f&&f.completedViews>f.impressions*.6?.08:0)),penalty=Math.min(.7,(f?.quickSkips??0)*.12+(f?.impressions??0)*.015);return{v,score:v.weight+bonus-penalty+rng()*.05}}).sort((a,b)=>b.score-a.score).map(x=>x.v)}
export const EMPTY_CATALOG:YouTubeShortsCatalog={schemaVersion:1,generatedAt:'1970-01-01T00:00:00.000Z',videos:[]};
export function catalogFromEnvironment(value: string | undefined): YouTubeShortsCatalog | null { if(!value)return null;const ids=[...new Set(value.split(',').map(x=>x.trim()).filter(x=>/^[\w-]{6,}$/.test(x)))];return ids.length?{schemaVersion:1,generatedAt:new Date().toISOString(),videos:ids.map(videoId=>({id:videoId,videoId,category:'other' as const,weight:1,enabled:true,addedAt:new Date().toISOString()}))}:null; }
